name: myblog2.0-server
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@master
      # 打包构建
      - name: Build
        uses: actions/setup-node@master
      - run: tar -zcvf release.tgz bin config controller data middlewares model mongodb router utils  .eslintrc.js index.js nodemon.json package-lock.json package.json

        # 发布 Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 上传构建结果到 Release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tgz
          asset_name: release.tgz
          asset_content_type: application/x-tgz

      # 部署到服务器
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.ALI_SSH_KEY }}
          connect_timeout: 60s
          first_ssh: |

          scp: |
            './release.tgz' => /home/www/Aimee/myblog2.0-server
          last_ssh: |
            cd /home/www/Aimee/myblog2.0-server
            tar -zxvf release.tgz 
            npm install
            npm run pm2:prod
