name: myblog2.0-server
on:
  push: 
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 下载源码
    - name: Checkout
      uses: actions/checkout@master
    # 打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: tar -zcvf release.tgz bin config controller data middlewares model mongodb router utils .editorconfig .eslintrc.js index.js nodemon.json package-lock.json package.json

    # 部署到服务器
    - name: Deploy
      uses:  cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        connect_timeout: 60s
        first_ssh: |
            cd /home/www/Aimee/myblog2.0-server
         scp: |
           './release.tgz' => /home/www/Aimee/myblog2.0-server
         last_ssh: |
            cd /home/www/Aimee/myblog2.0-server
            tar zxvf release.tgz 
            npm install
            npm run pm2:prod
